### ISSUE TITLE
Inspiration : Canadian maker passport

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/passeportMaker#5]
Je suis tombé dessus un peu par hasard : [Canadian maker passport](http://www.thingtanklab.com/makerpassport/about-the-maker-passport/). Apparemment, il existe depuis 2011. L'idée est d'aller choper des tampons dans les différents FabLabs, events, ... "ThinkHaus, Site3, Interaccess, Hacklab.to, SoOnCon, ThingTank Lab, kwartzlab, Diyode and unLondon"

Comme ils le disent eux-mêmes, c'est très très fortement inspiré du Hackerspace Passport dont on fait déjà référence ici. Hormis un branding canadien et maker, rien de bien nouveau en somme. Mais bon, ça fait une preuve de plus que le sujet intéresse et combiné au badge, ça peut devenir un bel outil.

Je l'ai mis sur [GitHub](https://github.com/Ginsburg/passeportMaker/blob/master/REFERENCE/canadian%20maker%20passport.pdf) si envie d'y jeter un coup d’œil.

**Comment by nicolasdb** [comment]
ha ouais, top.
encore un exemple mais qui neva pas plus loin que le hackerpassport de northbridge.

C'est tjs et uniquement pour collecter des "VISA" chez les fablab ou conventions.

**Comment by softrevolter** [comment]
c'est encore gentil hé :) ce weekend j'expliquais le concept à quelques vrais gamers, et ils trouvent vraiment bien foutu notre système de leveling, le clé va être dans les badges ils disent
